# 用于数组的文件输入输出

## 将数组以二进制格式保存到磁盘

In [ ]:
import numpy as np
arr = np.arange(10)
print arr
np.save('./data/some_array', arr)
print np.load('./data/some_array.npy')
np.savez('./data/array_archive.npz', a=arr, b=arr)
arch = np.load('./data/array_archive.npz')
print arch['b']
print arch['a']

## 存取文本文件

In [ ]:
!cat ./data/array_ex.txt

In [ ]:
arr = np.loadtxt('./data/array_ex.txt', delimiter=',')
print arr

# 线性代数

In [ ]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
print x
print y
print x.dot(y)
print np.dot(x, y)

print np.dot(x, np.ones(3))

from numpy.linalg import inv, qr
X = np.random.randn(5, 5)
mat = X.T.dot(X)
print inv(mat)
print mat.dot(inv(mat))
q, r = qr(mat)
print q
print r

# 随机数生成

In [24]:
samples = np.random.normal(size=(4,4))
print samples
from random import normalvariate
N = 1000000
%timeit samples = [normalvariate(0, 1) for _ in xrange(N)]
%timeit np.random.normal(size=N)

[[ 0.08416691  0.1113424   0.04292394 -0.56493665]
 [ 1.1879638   0.88601797 -1.19148876 -1.10428606]
 [ 2.03624452 -1.16590607 -1.0813298  -0.08262939]
 [ 0.84159591  1.31322015  1.22981175  0.70521639]]
1 loops, best of 3: 1.39 s per loop
10 loops, best of 3: 74.9 ms per loop
